client_id = "b100f326d39c4af6a848a6292cfb8291"
theme = "dracula"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists} {liked}
{album} • {genres}
{metadata}"""
playback_metadata_fields = [
    "repeat",
    "shuffle",
    "volume",
    "device",
]
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
progress_bar_position = "Bottom"
genre_num = 2
enable_media_control = true
enable_streaming = "Always"
enable_cover_image_cache = true
default_device = "spotify-player"
seek_duration_secs = 5
sort_artist_albums_by_type = false

[layout]
playback_window_position = "Top"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 70
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
